### ISSUE TITLE
Executes statements with "always:" tag don't specify output files and break CMake dependencies

### ISSUE THREAD

**Issue by EaselinkBachmann** [Open-CMSIS-Pack/cbuild2cmake#208]
When an output file of an `executes:` statement is needed by another executes statement or build rule, the build fails with:

```
ninja: error: '/home/user/solution/out/project/context/always_rule_output.bin', needed by '/home/user/solution/out/project/context/other_rule_output.bin', missing and no known rule to make it
```

~~Just adding `BYPRODUCTS` to the `add_custom_target` statement doesn't appear to be enough to fix it.~~

EDIT: I seem to have done something wrong when I first tested this yesterday. Adding BYPRODUCTS to `add_custom_target()`s with outputs fixes the issue.

## example executes statements

```yaml
  executes:
    - execute: generate-always
      run: python $input(0)$ -o $output(0)$
      always:
      input:
        - $SolutionDir()$/scripts/generate_always.py
      output:
        - $OutDir()$/always_rule_output.bin
    - execute: generate-other
      run: python $input(0)$ -i $input(1)$ -o $output$
      input:
        - $SolutionDir()$/scripts/generate_other.py
        - $OutDir()$/always_rule_output.bin
      output:
        - $OutDir()$/other_rule_output.bin
```

## relevant generated CMake

```cmake
# Execute: project+context-generate-always
set(INPUT
  ${SOLUTION_ROOT}/scripts/generate_always.py
)
list(GET INPUT 0 INPUT_0)
set(OUTPUT
  ${SOLUTION_ROOT}/out/project/context/always_rule_output.bin
)
list(GET OUTPUT 0 OUTPUT_0)
add_custom_target(project+context-generate-always ALL
  COMMAND python "${INPUT_0}"-o "${OUTPUT_0}"
  COMMENT project+context-generate-always
)

# Execute: project+context-generate-other
set(INPUT
  ${SOLUTION_ROOT}/scripts/generate_other.py
  ${SOLUTION_ROOT}/out/project/context/always_rule_output.bin
)
list(GET INPUT 0 INPUT_0)
list(GET INPUT 1 INPUT_1)
set(OUTPUT
  ${SOLUTION_ROOT}/out/project/context/other_rule_output.bin
)
add_custom_target(project+context-generate-other ALL DEPENDS ${OUTPUT})
add_custom_command(OUTPUT ${OUTPUT} DEPENDS ${INPUT}
  COMMAND python "${INPUT_0}" -i "${INPUT_1}"-o "${OUTPUT}" 
  COMMENT project+context-generate-other
)
```
